### ISSUE TITLE
very small difference from mainline portable installs

### ISSUE THREAD

**Issue by Ae3NerdGod** [Kryptuq/Yuzu-Early-Access-files#1]
using the mainline yuzu, you can make it portable by adding a folder called "User" in the root folder of yuzu. in this version, it seems to be case-sensitive and only allow "user" and not "User"

**Comment by Kryptuq** [comment]
> using the mainline yuzu, you can make it portable by adding a folder called "User" in the root folder of yuzu. in this version, it seems to be case-sensitive and only allow "user" and not "User"

i think u mean the installer with that^^ this is just the source code. 

post the issue here: https://github.com/MostlyWhat/128Bit-Yuzu-Installer

**Comment by Ae3NerdGod** [comment]
No, i dont mean the installer. I mean, if i download yuzu mainline from GitHub, extract the zip, and add a folder called `User` to the directory i extracted yuzu mainline too, it will use that folder instead of appdata to store data

If i do the same thing with the zip in releases of this gihub repo, not using the installer at all, it ignores the folder named `User` unless i rename it to `user` then it works the same as mainline yuzu, and becomes a portable install. 

I have not used that installer, nor do i plan to, because i need it portable, not installed

**Comment by beyondmeat** [comment]
The plugins folder on my Windows system using the installer is lower case. When I consulted the documentation when looking for a portable mode, it uses lower case 'user' and I made my user folder 'user' accordingly.

Delete/rename the old User folder. Create a folder called 'user' and then rename it 'User'. That might sound silly but it works. This is a neat filesystem trick with case sensitive code.

I would insist on keeping it user as that's just what the code expects and how it's intended.  case sensitive file systems like Linux, you would understand

**Comment by Ae3NerdGod** [comment]
> The plugins folder on my Windows system using the installer is lower case. When I consulted the documentation when looking for a portable mode, it uses lower case 'user' and I made my user folder 'user' accordingly.
> 
> I would insist on keeping it user as that matches what yuzu mainline does with plugins, it's lower case. It also matches the docs.
> 
understandable. 

> If you insist, make a folder called 'user" and then rename it into 'User'. It might seem silly but its a neat filesystem trick.

interesting. this works on ntfs and exfat/fat32? do you know why it works? just curious
