### ISSUE TITLE
Sound is broken in Mario Odyssey after updating to 3247

### ISSUE THREAD

**Issue by KingKebab** [Kryptuq/Yuzu-Early-Access-files#10]
Sound is very metalised in Mario Odyssey, and particulary while you swim under water and in the snow level.
The 3252 update doesn't fix the issue.

I also note huge slowdowns in Mario 3D World at world 2 first level when hearing the wind.

Everything was working fine in the 3246 release.

**Comment by Kryptuq** [comment]
thats something yuzu need to take care of.

I'm just offering Yuzu EA's for free, im not the team of yuzu or anything.
