### ISSUE TITLE
remove .pdb files from release

### ISSUE THREAD

**Issue by mercury233** [Kryptuq/Yuzu-Early-Access-files#2]
.pdb files are just for debug, not required for running, removing them will make the download file much smaller. If any user really want to debug the emulator, should compile the program on self.

**Comment by Kryptuq** [comment]
i know but people wanted it to have it in there^^ so i keep it

**Comment by d3xMachina** [comment]
Could you add an option in the installer (like in the modify section) to remove the pdb files as a opt in ?
