### ISSUE TITLE
compile yuzu with `YUZU_USE_QT_WEB_ENGINE` enabled

### ISSUE THREAD

**Issue by soredake** [Kryptuq/Yuzu-Early-Access-files#3]
Can you please compile your build with this option?

Without it yuzu will not have "report compatibility" option.

**Comment by Kryptuq** [comment]
i have it enabled for EA2725. so any further builds will have this option enabled.
keep in mind that this increases the filesize by +60MB atleast.

**Comment by soredake** [comment]
@Kryptuq option is still not showing, i was wrong thinking this build option adds it. Another builds of yuzu EA have this option working https://github.com/pineappleEA/pineapple-src, but updater for them is broken https://github.com/sinscove/Yuzu-Updater so i migrated to 128Bit-Yuzu updater.

**Comment by Kryptuq** [comment]
@soredake ok i will take a look at it again.

also for pineapple EA the Sinscove updater is super outdated and he isnt really working on it anymore.
Pineapple EA has its own Updater which u can find here: https://github.com/pineappleEA/liftinstall

its working like your Updater i assume but i didnt tested it yet. :)

**Comment by MostlyWhat** [comment]
It's the same installer framework, but I haven't tested also.

**Comment by MostlyWhat** [comment]
I think we should remove the qtweb engine again to reduce size.

**Comment by Kryptuq** [comment]
@MostlyWhat yeah we can disable that again in the next update,

ENABLE_COMPATIBILITY_REPORTING should be command for enabling it

**Comment by soredake** [comment]
> @MostlyWhat yeah we can disable that again in the next update,
> 
> ENABLE_COMPATIBILITY_REPORTING should be command for enabling it

It would be nice if you're enable this option in your builds too.

**Comment by Kryptuq** [comment]
@soredake report compatibility is now activated on EA2728 and further. 
please check and tell me if everything works.

@MostlyWhat also deactivated QTWeb engine again since its not needed for that 👍

**Comment by MostlyWhat** [comment]
@Kryptuq Thanks again!

**Comment by soredake** [comment]
> @soredake report compatibility is now activated on EA2728 and further. please check and tell me if everything works.
> 
> @MostlyWhat also deactivated QTWeb engine again since its not needed for that 👍

Option is now available, thanks.
