### ISSUE TITLE
Vulkan end Yuzu 2919 Blackscreen

### ISSUE THREAD

**Issue by DankKoolaid** [Kryptuq/Yuzu-Early-Access-files#5]
I recently Installed Yuzu early access 2919 version when I stated to play Metroid Dread the sound and controller works but does not show the menu all I see Is a black screen so I check the settings then set up to OpenGL as my graphics setting turns out  It goes back to normal the screen is shown the menu but when I set it back to Vulkan on my configuration is went back black screen. I think the Vulkan end is broken at this time so is best set to OpenGL until it gets fixed.

**Comment by technoir1989** [comment]
I'm having the same issue, Monster Hunter Generations Ultimate launches into a black screen with vulkan enabled.

**Comment by ElasiJM** [comment]
I don't know if it's for the same thing but before I had problems with the Nvidia driver version 516.xx, I changed to the driver version 512.15 and I no longer have problems with crashes or black screens

**Comment by technoir1989** [comment]
> I'm having the same issue, Monster Hunter Generations Ultimate launches into a black screen with vulkan enabled.

I forgot to mention that I'm using an RTX 3060 Ti with the latest drivers and a Ryzen 5600.

**Comment by infirit** [comment]
Just go back to 2916

**Comment by technoir1989** [comment]
> Just go back to 2916

I did that but the screen is still black and yuzu crashes after a little while.

**Comment by Endymi0n74** [comment]
fixed on 2920
