### ISSUE TITLE
Is this allowed or not?

### ISSUE THREAD

**Issue by OsoaGH** [Kryptuq/Yuzu-Early-Access-files#6]
You're meant to get EA through Patreon, do the Yuzu devs allow this repo to share the builds? Or do they not care if you build it yourself / share that build?

**Comment by Kryptuq** [comment]
yuzu ea is open source, u can build everything yourself if you want.
so they don't care if you build it yourself but might care about sharing it because it hurts their "income".

But this is where i dont care ^^. Since it's open source i can do whatever i want.

**Comment by infirit** [comment]
IANAL but the licence allows this as long as you the source is provided as well. https://github.com/yuzu-emu/yuzu/blob/master/LICENSE.txt
