### ISSUE TITLE
EA3164 corrupted with IDP.ARES.GENERIC virus...

### ISSUE THREAD

**Issue by curly72alpha** [Kryptuq/Yuzu-Early-Access-files#9]
HI... 
I downloaded your EA3164.
It was corrupted with IDP.ARES.GENERIC virus... scanned by 'AVAST ONE program'.

Your other release versions have or have not IDP.ARES.GENERIC virus...also.
Please check the issue...

**Comment by infirit** [comment]
It's a false positive. Avast is known to report emulators with some sort of jit or recompiler as infected.

**Comment by Kryptuq** [comment]
yeah.

Don't use Avast, its dogshit and also a false positive.
i suggest you uninstall Avast right away.
